proc freq data=my.liver_cmp;
	table med_cmp;
	run;
data cmp;
set my.liver_cmp;
	diagnosis=lowcase(med_cmp);
	run;
proc freq;
table diagnosis;
run;
data cmp;
set my.liver_cmp;
diagnosis=lowcase(med_cmp);
Depression="N";
if index(diagnosis,"depress") > 0  then Depression="Y";
AntiSocial="N";
if index(diagnosis,"antisocial") > 0 then AntiSocial="Y";
Anxiety="N";
if substr(diagnosis,1,3)="anx" then Anxiety="Y";
AcuteStress="N";
if index(diagnosis,'stress') > 0 or index(diagnosis,"stess") > 0 or diagnosis="asd" then AcuteStress="Y";
run;
proc freq;
table  depression AntiSocial Anxiety AcuteStress;
run;
