proc sort data=weight4;
by caseID;
run;
proc sort data=Height0;
by caseID;
run;
data BMI4;
format BMI4 4.1;
merge height0 weight4 ;
by caseID;
height0=height0/100;
BMI4 = weight4/height0**2;
if missing(BMI4) then delete;
keep caseID BMI4 ;
run;
proc sgplot data =BMI4;
histogram BMI4;
run;
proc freq data=BMI4 order=freq;
table bmi4 caseID;
run;
proc sort data=f13.final_r4;
by caseID;
run;
data  f13.final_r4;
merge f13.final_r3 (in=BL) BMI4;
by caseID;
if BL;
run;
proc freq data=f13.final_r4 order=freq;
table caseID;
run;
