proc sort data=weight0;
by caseID;
run;
proc sort data=Height0;
by caseID;
run;
data BMI;
format BMI0 4.1;
merge height0 weight0 ;
by caseID;
height0=height0/100;
BMI0 = weight0/height0**2;
if missing(BMI0) then delete;
if BMI0 < 30 then delete;
keep caseID BMI0 ;
run;
proc sgplot data =BMI;
histogram BMI0;
run;
proc freq data=BMI order=freq;
table bmi0 caseID;
run;
proc sort data=f13.final_r2;
by caseID;
run;
data  f13.final_r3;
merge f13.final_r2 (in=BL) BMI;
by caseID;
if BL;
if bmi0 < 30.0 then delete;
if patient_age le 18 then delete;
run;
proc freq data=f13.final_r3 order=freq;
table caseID;
run;
