/*
 This file is auto-generated by the statrep package.
 Do not edit this file or your changes will be lost.
 Edit the LaTeX file instead.
 
 See the statrep package documentation and the file
 statrep.cfg for information on these settings.
 */
 
 
%include "LaRoche_Assignment3_CPH576D_SR_preamble.sas" /nosource;
/* Remove all output files. */
%hostdel

/* Start program with a null title. */
title;

/*create dummy variables for race and female*/
data gfr;
set class.test_sample_3b;
if (r_gender = 'U' or r_gender = '') then r_gender = .; /*set U or blank to missing in gender*/
if r_gender = . then fem = .;
if r_gender = 'F' then fem = 1;
if r_gender = 'M' then fem = 0;
if r_race = 'AfrAmeri' then blk = 1;
  else blk = 0;
run;

/*use arrays to loop through each CR measurement
and calculate eGFR*/
data egfr;
set gfr;
array cr{4} CR_1M--CR_3Y;
array eg{4} egfr_1M egfr_6M egfr_1Y egfr_3Y;
do i=1 to 4;
egfr_base = 186*(cr{i}**-1.154)*(r_age**-0.203);
if (fem = 1 and blk = 1) then eg{i} = egfr_base*1.21*0.742;
if (fem = 1 and blk = 0) then eg{i} = egfr_base*0.742;
if (fem = 0 and blk = 1) then eg{i} = egfr_base*1.21;
if (fem = 0 and blk = 0) then eg{i} = egfr_base;
end;
drop i egfr_base;
run;


/* ceate ckd stages- care must be taken since the range of egfr
is outside the values for ckd stage.
I will create a stage 0 which indicates healthy kidney function.
Also missing values are considered very
small numbers so I will have to be careful of those*/

data ckd;
set egfr;
if (egfr_1M > 100) then ckdstg = 0;
if (90 le egfr_1M le 100) then ckdstg = 1;
if (60 le egfr_1M lt 90) then ckdstg = 2;
if (30 le egfr_1M lt 60) then ckdstg = 3;
if (15 le egfr_1M lt 30) then ckdstg = 4;
if (0 le egfr_1M lt 15) then ckdstg = 5;
run;

/*Create dichotomous kidney function indicator
for males and females separately*/

data ckd;
set ckd;
array eg{4} egfr_1M -- egfr_3Y;
array kf{4} kfunc_1M kfunc_6M kfunc_1Y kfunc_3Y;
do i=1 to 4;

if (fem = 1) and (1 < eg{i} < 70) then kf{i} = 0;
if (fem = 1) and (70 < eg{i} >= 70) then kf{i} = 1;
if (fem = 0) and (1< eg{i} < 68) then kf{i} = 0;
if (fem = 0) and (68 < eg{i} >= 68) then kf{i} = 1;
end;
drop i;
run;

%output(gfr)
proc freq data=class.test_sample_3b;
tables r_age r_gender r_race;
run;

proc univariate data=egfr ;
var egfr_1M;
histogram;
run;

proc freq data=ckd;
tables ckdstg;
run;

proc freq data=ckd;
tables kfunc_1M*kfunc_3Y;
run;

%endoutput(gfr)

%write(gfra,store=gfr,type=listing) 

%write(gfra,store=gfr,type=graphic) 

